<html lang="fr">

<head>
    <meta charset="utf-8">
    <title>Newsletter</title>
    <meta name="description" content="Module JS1 - Exercice Icons">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <link href="css/lib/normalize.css" rel="stylesheet">
    <link href="css/lib/layout.css" rel="stylesheet">
    <link href="css/lib/theme.css" rel="stylesheet">
    <link href="css/newsletter.css" rel="stylesheet">
</head>

<body>
    <header class="banner">
        <a class="banner-link" href="index.php">
            <strong class="banner-title">Abonnez-vous à notre newsletter ! </strong>
            <small>C'est gratuit !</small>
        </a>
    </header>
    <main class="project">
        <form id="subscribe-form" action="index.php" method="POST">

             <!-- if (isset($success)) : ?>
                <p class="message success"><?= $success; ?></p>
             endif; ?> -->
             <?php if (isset($_SESSION['message'])) : ?>
                <p class="message success"><?= $_SESSION['message']; ?></p>
                <?php unset($_SESSION['message']);?>
            <?php endif; ?>
            <fieldset>
                <legend>Abonnez-vous à la newsletter !</legend>
                <div class="field-list">
                    <label for="email">Adresse email</label>
                    <input type="email" name="email" id="email" value="<?= $email ?>">
                    <?php if (isset($errors['email'])) : ?>
                        <p class="message error"><?= $errors['email']; ?></p>
                    <?php endif; ?>
                </div>
                <div class="field-list">
                    <label for="first_name">First name</label>
                    <input type="text" name="first_name" id="first_name" value="<?= $firt_name ?>">
                    <?php if (isset($errors['first_name'])) : ?>
                        <p class="message error"><?= $errors['first_name']; ?></p>
                    <?php endif; ?>
                </div>
                <div class="field-list">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" value="<?= $name ?>">
                    <?php if (isset($errors['name'])) : ?>
                        <p class="message error"><?= $errors['name']; ?></p>
                    <?php endif; ?>
                </div>
                
                <div class="field-list">
                    <label for="origin">How did you find us ?</label>
                    <select name="origin" id="origin">
                        <?php foreach ($origins as $origin) : ?>
                            <option value="<?= $origin['id']; ?>"><?= $origin['origine_label']; ?></option>   
                        <?php endforeach; ?>
                    </select>
                </div>
                <div>
                    <?php foreach($checkboxs as $checkbox): ?>
                        <label for="<?= $checkbox["id"];?>"> <?= $checkbox["label_checkbox"]; ?></label>
                        <input type="checkbox" name="checkbox[]" value="<?= $checkbox['id']; ?>"

                        <?php if (isset($_POST['checkbox']) and in_array($checkbox['id'], $_POST['checkbox']))
                        {
                        echo "checked";
                        } ?>>

                    <?php endforeach; ?>
                    <?php if (isset($errors['checkbox'])) : ?>
                        <p class="message error"><?= $errors['checkbox']; ?></p>
                    <?php endif; ?>
                </div>
                
                <input type="submit" value="Valider" class="btn">
            </fieldset>
        </form>
    </main>

    <footer id="mentions" class="mentions">
        <p><strong> &copy; Olivier Meunier</strong>
    </footer>


</body>

</html>